<script>
  import Saos from "saos";
  import OnconceptosLogo from "./svg/OnconceptosLogo.svelte";
  import Spin from "./svg/Spin.svelte";
  import { isMobile } from "../store";

  $: logoWidth = $isMobile ? 300 : 500;
  $: spinBottom = $isMobile ? -500 : -270;
</script>

<section>
  <div class="content">
    <OnconceptosLogo paddingLeft={0} type="white" width={logoWidth} />
    <p>
      Una miniserie de <b>MSD Oncología</b>, que te ayudará a entender mejor el
      impacto del tratamiento contra el cáncer
    </p>
  </div>
  <Saos
    animation={`slide-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both`}
  >
    <Spin width={600} bottom={spinBottom} right={-150} />
  </Saos>
</section>

<style>
  section {
    width: 100%;
    min-height: 40vh;

    position: relative;
    z-index: -5;

    overflow: hidden;
  }

  div.content {
    color: white;

    font-size: 25px;

    /* margin: 50px 5vw; */
    margin-top: 12vh;

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    width: 100%;
  }

  div.content p {
    margin: 0;
    margin-top: 40px;

    width: 85%;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-4-19 19:31:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
  @-webkit-keyframes -global-slide-left {
    0% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
    }
    100% {
      -webkit-transform: translateX(-100px);
      transform: translateX(-100px);
    }
  }
  @keyframes -global-slide-left {
    0% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
    }
    100% {
      -webkit-transform: translateX(-100px);
      transform: translateX(-100px);
    }
  }

  @media screen and (min-width: 1024px) {
    div.content {
      width: 50%;
      margin: 50px 5vw;
    }
  }

  @media screen and (max-width: 500px) {
    section {
      height: 85vh;
    }
  }
</style>
